// @ts-nocheck

/**
 * Canonical table/column contract for src/db/schema/current.sql.
 * Used by schema.test.ts to verify generated kuma.db matches the source DDL.
 */
export const expectedTables = [
    "api_key",
    "docker_host",
    "domain_expiry",
    "group",
    "heartbeat",
    "incident",
    "maintenance",
    "maintenance_status_page",
    "monitor",
    "monitor_group",
    "monitor_maintenance",
    "monitor_notification",
    "monitor_tag",
    "monitor_tls_info",
    "notification",
    "notification_sent_history",
    "proxy",
    "remote_browser",
    "setting",
    "stat_daily",
    "stat_hourly",
    "stat_minutely",
    "status_page",
    "status_page_cname",
    "tag",
    "user",
];

export const expectedTableColumns = {
    api_key: ["id", "key", "name", "user_id", "created_date", "active", "expires"],
    docker_host: ["id", "user_id", "docker_daemon", "docker_type", "name"],
    domain_expiry: ["id", "last_check", "domain", "expiry", "last_expiry_notification_sent"],
    group: ["id", "name", "created_date", "public", "active", "weight", "status_page_id"],
    heartbeat: [
        "id",
        "important",
        "monitor_id",
        "status",
        "msg",
        "time",
        "ping",
        "duration",
        "down_count",
        "end_time",
        "retries",
        "response",
    ],
    incident: [
        "id",
        "title",
        "content",
        "style",
        "created_date",
        "last_updated_date",
        "pin",
        "active",
        "status_page_id",
    ],
    maintenance: [
        "id",
        "title",
        "description",
        "user_id",
        "active",
        "strategy",
        "start_date",
        "end_date",
        "start_time",
        "end_time",
        "weekdays",
        "days_of_month",
        "interval_day",
        "cron",
        "timezone",
        "duration",
        "last_start_date",
    ],
    maintenance_status_page: ["id", "status_page_id", "maintenance_id"],
    monitor: [
        "id",
        "name",
        "active",
        "user_id",
        "interval",
        "url",
        "type",
        "weight",
        "hostname",
        "port",
        "created_date",
        "keyword",
        "maxretries",
        "ignore_tls",
        "upside_down",
        "maxredirects",
        "accepted_statuscodes_json",
        "dns_resolve_type",
        "dns_resolve_server",
        "dns_last_result",
        "retry_interval",
        "push_token",
        "method",
        "body",
        "headers",
        "basic_auth_user",
        "basic_auth_pass",
        "docker_host",
        "docker_container",
        "proxy_id",
        "expiry_notification",
        "mqtt_topic",
        "mqtt_success_message",
        "mqtt_username",
        "mqtt_password",
        "database_connection_string",
        "database_query",
        "auth_method",
        "auth_domain",
        "auth_workstation",
        "grpc_url",
        "grpc_protobuf",
        "grpc_body",
        "grpc_metadata",
        "grpc_method",
        "grpc_service_name",
        "grpc_enable_tls",
        "radius_username",
        "radius_password",
        "radius_calling_station_id",
        "radius_called_station_id",
        "radius_secret",
        "resend_interval",
        "packet_size",
        "game",
        "http_body_encoding",
        "description",
        "tls_ca",
        "tls_cert",
        "tls_key",
        "parent",
        "invert_keyword",
        "json_path",
        "expected_value",
        "kafka_producer_topic",
        "kafka_producer_brokers",
        "kafka_producer_ssl",
        "kafka_producer_allow_auto_topic_creation",
        "kafka_producer_sasl_options",
        "kafka_producer_message",
        "oauth_client_id",
        "oauth_client_secret",
        "oauth_token_url",
        "oauth_scopes",
        "oauth_auth_method",
        "timeout",
        "gamedig_given_port_only",
        "mqtt_check_type",
        "remote_browser",
        "snmp_oid",
        "snmp_version",
        "json_path_operator",
        "cache_bust",
        "conditions",
        "rabbitmq_nodes",
        "rabbitmq_username",
        "rabbitmq_password",
        "smtp_security",
        "ws_ignore_sec_websocket_accept_header",
        "ws_subprotocol",
        "ping_count",
        "ping_numeric",
        "ping_per_request_timeout",
        "ip_family",
        "manual_status",
        "oauth_audience",
        "mqtt_websocket_path",
        "domain_expiry_notification",
        "save_response",
        "save_error_response",
        "response_max_length",
        "system_service_name",
        "subtype",
        "location",
        "protocol",
        "snmp_v3_username",
        "expected_tls_alert",
        "retry_only_on_status_code_failure",
        "screenshot_delay",
        "bearer_token",
        "gamedig_token",
        "last_notification_at",
    ],
    monitor_group: ["id", "monitor_id", "group_id", "weight", "send_url", "custom_url"],
    monitor_maintenance: ["id", "monitor_id", "maintenance_id"],
    monitor_notification: ["id", "monitor_id", "notification_id"],
    monitor_tag: ["id", "monitor_id", "tag_id", "value"],
    monitor_tls_info: ["id", "monitor_id", "info_json"],
    notification: ["id", "name", "active", "user_id", "is_default", "config"],
    notification_sent_history: ["id", "type", "monitor_id", "days"],
    proxy: [
        "id",
        "user_id",
        "protocol",
        "host",
        "port",
        "auth",
        "username",
        "password",
        "active",
        "default",
        "created_date",
    ],
    remote_browser: ["id", "name", "url", "user_id"],
    setting: ["id", "key", "value", "type"],
    stat_daily: ["id", "monitor_id", "timestamp", "ping", "up", "down", "ping_min", "ping_max", "extras"],
    stat_hourly: ["id", "monitor_id", "timestamp", "ping", "ping_min", "ping_max", "up", "down", "extras"],
    stat_minutely: ["id", "monitor_id", "timestamp", "ping", "up", "down", "ping_min", "ping_max", "extras"],
    status_page: [
        "id",
        "slug",
        "title",
        "description",
        "icon",
        "theme",
        "published",
        "search_engine_index",
        "show_tags",
        "password",
        "created_date",
        "modified_date",
        "footer_text",
        "custom_css",
        "show_powered_by",
        "analytics_id",
        "show_certificate_expiry",
        "auto_refresh_interval",
        "analytics_script_url",
        "analytics_type",
        "show_only_last_heartbeat",
        "rss_title",
    ],
    status_page_cname: ["id", "status_page_id", "domain"],
    tag: ["id", "name", "color", "created_date"],
    user: ["id", "username", "password", "active", "timezone", "twofa_secret", "twofa_status", "twofa_last_token"],
};

export const expectedMonitorColumns = expectedTableColumns.monitor;
export const expectedStatusPageColumns = expectedTableColumns.status_page;
export const expectedUserColumns = expectedTableColumns.user;
export const expectedHeartbeatColumns = expectedTableColumns.heartbeat;

export const expectedIndexes = [
    "domain_expiry_domain_unique",
    "fk",
    "good_index",
    "heartbeat_important_index",
    "heartbeat_monitor_id_index",
    "maintenance_active_index",
    "maintenance_id_index2",
    "maintenance_user_id",
    "manual_active",
    "monitor_id_index",
    "monitor_important_time_index",
    "monitor_notification_index",
    "monitor_remote_browser_index",
    "monitor_time_index",
    "notification_sent_history_type_monitor_id_days_unique",
    "proxy_user_id",
    "setting_key_unique",
    "stat_daily_monitor_id_timestamp_unique",
    "stat_hourly_monitor_id_timestamp_unique",
    "stat_minutely_monitor_id_timestamp_unique",
    "status_page_cname_domain_unique",
    "status_page_slug_unique",
    "user_username_unique",
];
